# syntax=docker/dockerfile:1

FROM debian:latest

# Install dependencies
RUN apt-get -y update && \
 apt-get -y install nginx && \
 apt-get -y install git && \
 apt-get -y install sudo && \
 apt-get -y install openjdk-21-jre && \
 apt-get -y install node && \