# syntax=docker/dockerfile:1

FROM mcr.microsoft.com/devcontainers/base:ubuntu
# Install the xz-utils package
RUN apt-get update && \
    apt-get install openjdk-21-jre && \
    apt-get install nodejs && \
    apt-get install npm && \
    apt-get install git
