name: Salesforce Full Validation Job

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  REPO_NAME: ${{ github.event.repository.name }}
  SERVER_URL: ${{ github.server_url }}
  REPOSITORY: ${{ github.repository }}
  BRANCH: ${{ github.head_ref }}
  JWT_KEY: ${{ secrets.JWT_KEY }}
  CLIENT_KEY: ${{ secrets.CLIENT_KEY }}
  USER_NAME: ${{ secrets.USER_NAME }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Code-Scan:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: Production
    # Use salesforcedx container
    container:
      image: salesforce/salesforcedx:latest-full
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}

      - name: Install code analysis plugin
        run: sfdx plugins:install @salesforce/sfdx-scanner

      - name: Run code scan
        run: sfdx scanner:run --target "force-app/main/default" --engine "eslint-lwc,retire-js,cpd,pmd" --verbose

  Full-Validation:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: Production
    # Use salesforcedx container
    container:
      image: salesforce/salesforcedx:latest-full
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
      
      - name: Authorize with the org and set configuration
        run: chmod +x bash-scripts/AuthorizeAndSetConfig.sh && ./bash-scripts/AuthorizeAndSetConfig.sh

      - name: Running validation and test classes
        run: sfdx force:source:deploy -c -p force-app --testlevel RunLocalTests
